version: "2"

networks:
  backend:
    driver: bridge

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - "./mongo/data:/data/db"
    networks:
      - backend

  nodeAuth:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./database:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
    depends_on:
      - mongo
    networks:
      - backend
    
  nodeApp:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./regexMicroservice:/home/node/app
    ports:
      - "8023:8023"
    command: "npm start"

  proxy:
    image: "nginx:latest"
    ports:
      - "8080:443"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/nginx.conf
      - ./certificates/user/ca.crt:/etc/nginx/client_certs/ca.crt
      - ./certificates/server/server.crt:/etc/nginx/server_certs/server.crt
      - ./certificates/server/server.key:/etc/nginx/server_certs/server.key
    environment:
      - NGINX_HOST=Mikelangelo.com
      - NGINX_PORT=80
    
